library(twitteR)
library(ROAuth)
library(plyr)
library(stringr)

api_key = "ODYtHNYugVmGowquNqQiOVKrQ"
api_secret = "UoZyU7t1ejYryawBkXxJIPO8vZaxnevSA6f7bqL0NtdJIcz6il"
access_token = "4902638004-s5Uw5u4iPr4iYTCdYFDvmM7YRSj3NMuJQsZ7iWc"
access_secret = "MZwU9YcQdG0yUyNfAbLmf6haKu0ALRgKcxSzMpyz9joD0"

setup_twitter_oauth(api_key, api_secret, access_token=access_token, access_secret=access_secret)
statuses <- searchTwitter("@RussiaInsider", lang = "en", n=5000)
df <- twListToDF(statuses)
write.csv(df$text, "russia_insider.csv", row.names = FALSE)

library(tm)
library(wordcloud)

# load the text into a so-called corpus
k <- Corpus(DirSource("./temp/"), readerControl = list(language = "en"))
k <- tm_map(k, removeNumbers)
k <- tm_map(k, stripWhitespace)
k <- tm_map(k, tolower)
k <- tm_map(k, removeWords, stopwords("english"))
k <- tm_map(k, removePunctuation)

# carry out text stemming (process for reducing inflected (or sometimes derived) words to their word stem)
k <- tm_map(k, stemDocument)

k <- tm_map(k, PlainTextDocument)

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("russians", "russian", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("russias", "russia", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("clintons", "clinton", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("brussels", "brussel", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("years", "year", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("youtub", "youtube", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("worldwid", "worldwide", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("wrussia", "russia", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("worrying", "worry", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("worlds", "world", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("works", "work", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("working", "work", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("workers", "work", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("words", "word", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("womanintransit", "woman", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("weaponising", "weapon", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("weaponized", "weapon", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("weapons", "weapon", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("washingtons", "washington", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("wanted", "want", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("wants", "want", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("voted", "vote", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("voter", "vote", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("voters", "vote", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("votersuppression", "vote", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("violators", "violence", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("violators", "violence", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("violent", "violence", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("violated", "violence", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("usrussian", "russian", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("useless", "use", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("uses", "use", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("uniting", "unite", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("uniting", "unite", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("ukranian", "ukrainian", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("ukriane", "ukraine", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("ukraines", "ukraine", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("turkeys", "turkey", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("turks", "turkey", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("turnaround", "turn", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("turned", "turn", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("terrorism", "terror", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("terrorist", "terror", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("terrorists", "terror", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("terrorized", "terror", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("syrians", "syrian", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("syrias", "syria", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("stupidity", "stupid", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("strategi", "strategy", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("stories", "story", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("steps", "step", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("states", "state", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("sends", "send", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("says", "say", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("said", "say", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("russiain", "russia", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("russiainsi", "russia", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("returning", "return", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("returned", "return", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("reports", "report", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("remains", "remain", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("refugee", "refuge", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("ratings", "rating", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("putins", "putin", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("prepares", "prepare", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("attacks", "attack", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("abandoned", "abandon", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("abandoning", "abandon", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("accounts", "account", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("admits", "admit", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("admitted", "admitt", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("americans", "american", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("armi", "army", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("failed", "fail", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("failing", "fail", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("fails", "fail", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("fighters", "fight", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("fighting", "fight", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("forc", "force", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("forces", "force", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("forcing", "force", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("fought", "fight", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("games", "game", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("gets", "get", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("happens", "happen", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("happened", "happen", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("helped", "help", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("hidden", "hide", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("hiding", "hide", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("hillaryclinton", "hillary", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("insiders", "insider", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("journalists", "journalist", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("kills", "kill", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("killed", "kill", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("lackeys", "lackey", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("leaders", "leader", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("liked", "like", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("masterpiecee", "masterpiece", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("means", "mean", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("muslims", "muslim", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("needed", "need", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("needs", "need", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("newsbud", "news", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("obamas", "obama", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("attacks", "attack", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("bombings", "bombing", x)})

k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("brusselattack", "brussel", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("celebrates", "celebrate", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("played", "play", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("playing", "play", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("poroshenkoampco", "poroshenko", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("bombings", "bombing", x)})
k[[1]]$content <- lapply(k[[1]]$content, function(x) {gsub("http+", "", x)})

rem <- c("russiainsid", "russiainsider", "htt", "condemns", "still", "now", "video", "via")

k <- tm_map(k, removeWords, rem)
tdm <- as.matrix(TermDocumentMatrix(k))
df1 <- data.frame(word = rownames(tdm), freq = tdm, stringsAsFactors = FALSE)
df1 <- df1[!grepl("http+", df1$word),]

wordcloud(df1$word, df1$character.0., random.order=FALSE, colors=brewer.pal(8, "Dark2"), min.freq = 30)

write.csv(df1, "words.csv", row.names = FALSE)
